### ISSUE TITLE
OUT_OF_HOST_MEMORY

### ISSUE THREAD

**Issue by Serezha2H** [TON-Pool/miner#17]
ton-pool.com-miner-0.3.4
https://github.com/TON-Pool/miner/releases/download/0.3.4/ton-pool.com-miner-0.3.4-hiveos.tar.gz
Already installed
2021-12-27 13:34:29,355 [INFO] starting TON-Pool.com Miner 0.3.4 on pool https://server1.whalestonpool.com wallet  ...
2021-12-27 13:34:30,187 [INFO] total devices: 1
Traceback (most recent call last):
  File "_miner.py", line 510, in <module>
  File "_miner.py", line 237, in __init__
pyopencl._cl.RuntimeError: CommandQueue failed: OUT_OF_HOST_MEMORY
[14976] Failed to execute script '_miner' due to unhandled exception!

only one VideoCard is R9 280, installed in x16 slot, system has a 8 gb ram (7 free)
hiveos 0.6-212@211130 
A 20.40 (5.11.1001)
N 470.86
DRIVERS

Where is problem? Thank you

**Comment by Runningwarrior08** [comment]
I don't think this miner works on whales pool.
