### ISSUE TITLE
Exception: ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by mistercx** [TON-Pool/miner#22]
Hi! I try to run miner.py and I have an exception:

Traceback (most recent call last):
  File "c:\Mining\TONCOIN\source\miner.py", line 145, in update_task
    load_task(r, '/job', (pool_url, wallet))
  File "c:\Mining\TONCOIN\source\miner.py", line 106, in load_task
    hash_state = np.array(sha256.generate_hash(input[:64])).astype(np.uint32)
ValueError: invalid literal for int() with base 10: b'?\x02t\xde[b6\x1eS\xe3\xe4z\x17\xe3G\xf8\xdc\xa1\xb1z\x89\xc3`\xa21y\x03\xed-\x0c\xd1&'

**Comment by mistercx** [comment]
Fixed
