### ISSUE TITLE
Failed to execute script '_miner' due to unhandled exception!

### ISSUE THREAD

**Issue by ErfanBahramali** [TON-Pool/miner#23]
OS: Ubuntu 20.04

Command:

```./miner-linux https://next.ton-pool.com wallet```
```./miner-linux https://next.ton-pool.club wallet```

Result:

```
2022-01-05 16:51:04,240 [INFO] starting TON-Pool.com Miner 0.3.4 on pool https://next.ton-pool.club wallet wallet ...
Traceback (most recent call last):
  File "_miner.py", line 457, in <module>
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
[425277] Failed to execute script '_miner' due to unhandled exception!

```

**Comment by Nightprince** [comment]
It also gives the same error in Windows.

```2023-05-19 12:25:36,501 [INFO] starting TON-Pool.com Miner 0.3.4 on pool https://next.ton-pool.club wallet ...
Traceback (most recent call last):
  File "_miner.py", line 438, in <module>
  File "requests\models.py", line 910, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[5928] Failed to execute script '_miner' due to unhandled exception!
[process exited with code 1 (0x00000001)]
```


OS: Windows 11

**Comment by AmirrezaFiroz** [comment]
how can we fix that?
